# Generated by Django 3.1.7 on 2021-03-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan_active',
            field=models.BooleanField(default=False),
        ),
    ]
