# Generated by Django 3.1.7 on 2021-03-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0002_user_plan_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institution_name',
            field=models.CharField(default='', editable=False, max_length=300),
        ),
    ]
