# Generated by Django 3.1.7 on 2021-03-23 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign_up', '0003_user_institution_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='institution_name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
