# Generated by Django 3.1.7 on 2021-03-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhyEduVueText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_text', models.CharField(max_length=300)),
                ('abbrivationtext', models.CharField(max_length=500)),
                ('display', models.BooleanField()),
            ],
        ),
    ]
