# Generated by Django 3.1.7 on 2021-03-23 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sign_up', '0004_auto_20210323_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('subject', models.CharField(max_length=300)),
                ('password', models.CharField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('attendance', models.PositiveIntegerField()),
                ('salary', models.PositiveIntegerField()),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign_up.user')),
            ],
        ),
    ]
